- aulas/09.md
Acrescentadas pequenas observações para aprimorar o entendimento do capítulo.
- Lint do arquivo markdown
- Adicionada revisão do tópico de criação do Dockerfile
- Acrescentadas observações descrevendo o comando `poetry run`
- Adicionada verificação para garantir que a imagem foi gerada
- Aprimorada descrição para rodar o contêiner
> Docs: Adicionadas anotações no módulo de Docker

- README.md
Tabs por 2 espaços e novas linhas depois dos headers
> Formatado com Prettier

- aulas/01.md
- aulas/02.md
- aulas/03.md
- aulas/04.md
- aulas/05.md
- aulas/06.md
- aulas/07.md
- aulas/08.md
- aulas/11.md
- plano.md
Pequenas correções e remoção de espaços no final da linha
> TXT: Pequenas correções + .strip()

- aulas/02.md
Pequeno ajuste no subtítulo para seguir o padrão dos demais.
> TXT: ajuste de subtitulo

- aulas/README.md
> [SUG] pequenas sugestões e trailing

- aulas/08.md
Corrigindo palavra "tarrefas" para "tarefas" na linha 336 de aula/08.md
> fix: corrigindo palavra "tarrefas"

- aulas/03.md
1. Adicionado o arquivo settings.py no diagrama do projeto, conforme explicado no tutorial.
2. Realizada a organização dos imports no arquivo test_db.py conforme a formatação.
> Adicionar settings.py no diagrama e organizar import no test_db.py

- aulas/01.md
> Explicitando o motivo da versão 3.11 de Python

- aulas/02.md
Tinha uma frase inteira repetida, estou sugerindo um ajuste nisso. Também acertei o nome Swagger, com S maiúsculo.
> Removendo frase repetida, e acertando nome Swagger

- aulas/04.md
- aulas/08.md
Pequenos typos que encontrei no capitulo  4 e 8.
> Acerta pequenos typos

- aulas/README.md
percebi essa duplicação que talvez passou despercebida
> removendo texto duplicado da sessao de conclusao

- aulas/09.md
- codigo_das_aulas/08/Dockerfile
Corrige o Dockerfile
Faz uns ajustes no texto da aula 09
> Compose 09

- aulas/06.md
- codigo_das_aulas/06/fast_zero/routes/users.py
- codigo_das_aulas/07/fast_zero/routes/users.py
- codigo_das_aulas/08/fast_zero/routes/users.py
- [WIP] Adicionando alterações no endpoint de PUT
- [WIP] Adicionando alterações no endpoint de PUT
> Adicionando alterações da aula 05 as aulas seguintes

- aulas/06.md
- aulas/07.md
- codigo_das_aulas/06/fast_zero/routes/auth.py
- codigo_das_aulas/06/tests/conftest.py
- codigo_das_aulas/06/tests/test_auth.py
- codigo_das_aulas/07/fast_zero/routes/auth.py
- codigo_das_aulas/07/tests/conftest.py
- codigo_das_aulas/07/tests/test_auth.py
- [WIP] Adição do prefixo 'auth' no router da aula 06
- [WIP] Trazendo alterações do router da aula 06 para 07
> Adicionando prefixo de router na aula 06 e seguintes

- aulas/05.md
> FIX: Ajustes na alteração dos endpoints que usam hash.

- aulas/05.md
O current user foi definido antes da hora, problemas de merge
relates #46
relates #51
Obrigado ao @Andre-Almeida-Numb3rs que encontrou esse bug
> [FIX] Ajustando `current_user` na aula 05

- aulas/03.md
> [WIP] Adição das anotações de tipos do alembic na aula 03

- aulas/12.md
> [WIP] - Revisão da aula 12

- aulas/01.md
- aulas/02.md
- aulas/03.md
- aulas/04.md
- aulas/05.md
- aulas/06.md
- aulas/07.md
- aulas/08.md
- aulas/09.md
- aulas/10.md
- aulas/11.md
- aulas/README.md
Manutenção na abertura, agora que todo o texto está em sua versão final!
closes #66
> Manutenção da aula 00

- aulas/01.md
Fecha issue https://github.com/dunossauro/fastapi-do-zero/issues/76
> Ajusta codigo do teste da aula 01

- aulas/03.md
> Corrige: comando para instalação do sqlite 3 em Debian/Ubuntu

- aulas/02.md
- aulas/03.md
- aulas/04.md
- aulas/05.md
Correções:
Aula 2:
- Alterado de **Criar uma básica teórica[...]** para **Criar uma base teórica[...]** nos objetivos da aula 2;
- Adicionado o **o** faltante ao descrever o protocolo HTTP;
- Alterado de **boolianos** para **booleanos** no tópico Contratos em APIs JSON;
Aula 3:
- Removido o **de** ao definir os códigos de resposta da API;
- Alterado de **Implementado endpoints** para **Implementando endpoints**;
- Removido o **h** no início de **omitido**;
- Corrigido o nome do arquivo de exemplo de **aula_00.py** para **fast_zero/app.py**
- Adicionado o **o** na descrição de requisição que foge dos padrões definidos no schema;
- Removido o **de** ao descrever o pydantic;
- Removido o **do** da mensagem de descrição do ResponseValidationError;
- Removido o **ele valor** no tópico …
> Correções aula 02 até aula 05

- aulas/01.md
Lendo o material durante os estudos notei um _typo_ que resolvi ajustar.
> Ajustando typo

- aulas/05.md
Eduardo, esse é meu primeiro PR. Espero ter feito tudo certo.
> Uma pequena correção de concordância no texto.

- aulas/01.md
- **criando o hyprlink para a documentação do pytest na Aula 1**
- close #105
> Colocando o hyprlink do site do pytest na aula 01 

- aulas/07.md
- Coloquei {:target=_blank} após o hyperlink do Soc
> Ajustando hyperlink aula na 07

- aulas/04.md
... com typo no nome da branch 🤦
> Correção de typo

- aulas/14.md
- aulas/projetos/projetos_finais.md
- aulas/projetos/repositorios.md
Adicionando páginas do projeto final do curso.
> Projeto final

- aulas/01.md
- aulas/02.md
- aulas/codigos/01/pyproject.toml
- codigo_das_aulas/01/poetry.lock
- codigo_das_aulas/01/pyproject.toml
- codigo_das_aulas/02/poetry.lock
- codigo_das_aulas/02/pyproject.toml
- codigo_das_aulas/03/poetry.lock
- codigo_das_aulas/03/pyproject.toml
- codigo_das_aulas/04/poetry.lock
- codigo_das_aulas/04/pyproject.toml
- codigo_das_aulas/05/pyproject.toml
- codigo_das_aulas/06/pyproject.toml
- codigo_das_aulas/07/pyproject.toml
- codigo_das_aulas/08/pyproject.toml
- codigo_das_aulas/09/pyproject.toml
- codigo_das_aulas/10/pyproject.toml
- codigo_das_aulas/11/pyproject.toml
- codigo_das_aulas/12/pyproject.toml
> Adicionando fastapi-cli no curso

- aulas/04.md
Tópico elencado em #141 
@lbmendes e @RWallan, poderiam dar uma lida antes de eu mergear? Eu tentei ser mais detalhista xD
> Ajustando a legibilidade das dataclasses na aula 04

- aulas/09.md
- codigo_das_aulas/09/fast_zero/schemas.py
- codigo_das_aulas/10/fast_zero/schemas.py
- codigo_das_aulas/11/fast_zero/schemas.py
- codigo_das_aulas/12/fast_zero/schemas.py
Soluciona issues https://github.com/dunossauro/fastapi-do-zero/issues/150 e https://github.com/dunossauro/fastapi-do-zero/issues/151
> Aula 09 - Ajusta class TodoUpdate e Teste test_delete_todo

- aulas/06.md
- aulas/07.md
- codigo_das_aulas/06/tests/test_security.py
- codigo_das_aulas/07/tests/test_security.py
- codigo_das_aulas/08/tests/test_security.py
- codigo_das_aulas/09/tests/test_security.py
- codigo_das_aulas/10/tests/test_security.py
- codigo_das_aulas/11/tests/test_security.py
- codigo_das_aulas/12/tests/test_security.py
> Adicionando teste para o decode do jwt

- aulas/01.md
Caro, boa tarde!
Segue pequena sugestão de contribuição com a documentação.
> Atualização da documentação

- aulas/05.md
Corrigi um erro de digitação na palavra 'session'
> Correção de typo: 'session'

- aulas/04.md
Linha de import do método func foi adicionada nesse snippet mas não estava com a marcação
> Atualização de highlight de código

- aulas/05.md
Seguem algumas sugestões de ajuste na aula 5.
> Pequenos ajustes aula 5

- aulas/08.md
correção do typo de reresh para refresh
> correção do typo para refresh

- mkdocs.yml
- overrides/assets/javascripts/extra.js
- overrides/main.html
- overrides/partials/fonts.html
- overrides/partials/header.html
Adicionando no cabeçalho da página um modo de configurar qual a fonte do texto e adicionando a fonte OpenDyslexic como opção.
> Adicionando alterador de fonte para poder configurar o OpenDyslexic

- aulas/stylesheets/extra.css
> Diminui padding dos botões

- aulas/03.md
- codigo_das_aulas/03/poetry.lock
- codigo_das_aulas/03/pyproject.toml
- codigo_das_aulas/04/poetry.lock
- codigo_das_aulas/04/pyproject.toml
- codigo_das_aulas/05/poetry.lock
- codigo_das_aulas/05/pyproject.toml
- codigo_das_aulas/06/poetry.lock
- codigo_das_aulas/06/pyproject.toml
- codigo_das_aulas/07/poetry.lock
- codigo_das_aulas/07/pyproject.toml
- codigo_das_aulas/08/poetry.lock
- codigo_das_aulas/08/pyproject.toml
- codigo_das_aulas/09/poetry.lock
- codigo_das_aulas/09/pyproject.toml
- codigo_das_aulas/10/poetry.lock
- codigo_das_aulas/10/pyproject.toml
- codigo_das_aulas/11/poetry.lock
- codigo_das_aulas/11/pyproject.toml
- codigo_das_aulas/12/poetry.lock
- codigo_das_aulas/12/pyproject.toml
Resultado da alteração pode ser vista aqui:
- https://taconi.github.io/fastapi-do-zero/03/#estendendo-a-validacao-com-e-mail
closes #244
> Removendo instalação do `pydantic[email]`

- aulas/08.md
da forma como estava o teste falhava, pois estava atualizando o usuario com o mesmo id da fixture user
> teste do endpoint de update um usuario tentando atualizar outro

- aulas/exercicios_resolvidos/aula_04.md
closes #279 
Só adicionei um redirect pra explicação da live e mostrei o ajuste na migração.
Deploy de teste: https://taconi.github.io/fastapi-do-zero/exercicios_resolvidos/aula_04/#solucao_3
> Migração em batch na exercício 4 da aula 4

- aulas/06.md
- changelogs/327.correcoes.md
- Pequena alteração de valores do status code
> alteração no texto da aula 06 onde aparecia 409 (Conflict) para 401 (Unauthorized)

- aulas/03.md
- aulas/exercicios_resolvidos/aula_03.md
- changelogs/376.correcoes.md
> Corrige typo na URL 127.0.0.1

- aulas/08.md
- changelogs/363.alterado.md
> Alteração no texto de instalação do sqlalchemy async
